<a href="https://colab.research.google.com/github/brettfazio/AI_Homework1/blob/master/HW_1/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Homework Problem 2 Specification:**

Inside a colab notebook implement a Python function multiply_matrices that takes as input a list of numpy arrays and outputs their product. It should raise a custom exception if there is a pair of incompatible matrices. The exception message should provide information about which pair of matrices is bad. Make sure that you follow the style guide for Python.

Make this notebook editable (so the TAs can directly put comments in the notebook), obtain a sharable link, enter it in Webcourses, and also save this notebook to your GitHub repo inside the folder called HW_1.

In [0]:
import numpy as np

def multiply_matrices(matrices):
  if (len(matrices) == 0):
    return np.array([0])
  result = matrices[0]

  # Skip the first matrix as we set it as the result, iterate through the rest
  i = 1
  while i < len(matrices):
    # Make sure the shapes are the same, raise an exception otherwise.
    if result.shape != matrices[i].shape:
      raise Exception('Matrices {} and {} do not have the same shape. Cannot be multipled.'.format(i-1, i))
    
    result = result * matrices[i]
    i = i + 1
  
  return result


The following are just a couple tests.

In [21]:
mats = [np.array(([[0,1,2,3], [4,5,6,7], [8,9,10,11]])), 
        np.array(([[0,1,2,3], [4,5,6,7], [8,9,10,11]])),
        np.array(([[0,1,2,3], [4,5,6,7], [8,9,10,11]]))]

print(multiply_matrices(mats))

[[   0    1    8   27]
 [  64  125  216  343]
 [ 512  729 1000 1331]]


Following test should throw an exception

In [20]:
failing_test = [np.array(([[0,1,2,3], [4,5,6,7], [8,9,10,11]])),
                np.array([[1,2,3],[2,3],[2,43,32]])]
  
print(multiply_matrices(failing_test))

Exception: ignored